### ISSUE TITLE
Issue with imports and dependencies

### ISSUE THREAD

**Issue by cpdl1997** [unitn-sml/pear-personalized-algorithmic-recourse#1]
Unable to run the code due to dependency issue:
1) in blackbox/adult/adult_scm:  from recourse_fare.utils.wfare_utils.structural_weights import StructuralWeights
2) in utils: from recourse_fare.models.WFAREFiner import WFAREFiner

Please also specify python version, and update the versions for tensorflow, tensorboard, torch and numpy in keeping with other dependencies.

**Comment by geektoni** [comment]
Hi, we updated the repository with instructions on installing the required dependencies and running the PEAR code. Regarding the Python version, we used 3.7 and all the various model checkpoints require it and they also require that the other dependencies versions (as reported in `requirements.txt`) should match. 

Please let us know if you have any other trouble!
